version: 2.0.{build}
os: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts
  name: artifacts